import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ==========================================
# CONFIGURATION
# ==========================================
DATASET_DIR = "dataset"
IMG_SIZE = (64, 64)
BATCH_SIZE = 32
EPOCHS = 30 # 10 passes through the data is usually plenty for this

print("Loading Dataset...")

# Load Training Data (80% of the images)
train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    DATASET_DIR,
    validation_split=0.2,
    subset="training",
    seed=123,
    color_mode="grayscale", # Grayscale is faster and color doesn't matter for letters
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# Load Validation Data (20% of the images to test accuracy during training)
val_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    DATASET_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    color_mode="grayscale",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# Get the exact labels (A, B, C... Z, QU) generated by the folders
class_names = train_dataset.class_names
print(f"Found {len(class_names)} classes: {class_names}")

# Optimize dataset loading for speed
AUTOTUNE = tf.data.AUTOTUNE
train_dataset = train_dataset.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_dataset = val_dataset.cache().prefetch(buffer_size=AUTOTUNE)

# ==========================================
# BUILD THE CNN ARCHITECTURE
# ==========================================
print("Building the Model...")

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(64, 64, 1)),

    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),

    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

model.summary()

# ==========================================
# TRAIN THE MODEL
# ==========================================
print("Starting Training...")
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=EPOCHS
)

# Save the finished brain to your hard drive!
model.save('perfect_ocr_model.h5')
print("\nModel saved as 'perfect_ocr_model.h5'!")

# Plot the training results (so you can visually see how smart it got)
plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()